server:
  port: 8081
spring:
  redis:
    host: 192.168.87.130
    port: 6379
    timeout: 2000
  datasource:
    url: jdbc:mysql://192.168.87.130:3306/taboo_game?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret-key: mummy-lll
  expiration-time: 7200000   # 过期时间，单位毫秒（比如2小时）
  enable-expiration: true    # 是否开启过期时间校验
  # redis-expiration-time: 3600000
  redis-expiration-time: 900000